Repository God-s-favourite-programmers/ababot, pull requests merged in 2021-05, with the labels that each got.

#80 Improved restart
  src/cogs/abakus/abakus.py
  src/main.py
Labels: enhancement

#81 Docstrings and import sorting
  src/cogs/abakus/abakus.py
  src/cogs/soup/soup.py
  src/main.py
Labels: documentation

#88 Fix channel content check
  src/cogs/abakus/abakus.py
  src/cogs/cleaning/cleaning.py
Labels: bug

#89 Cancel on restart with sleep time
  src/cogs/abakus/abakus.py
Labels: bug

#92 Abakus refactor
  src/cogs/abakus/abakus.py
  src/cogs/abakus/async_helpers.py
  src/cogs/abakus/event.py
  src/cogs/abakus/event_parser.py
  src/cogs/abakus/helper_functions.py
Labels: enhancement

#94 Custom help messages
  src/cogs/abakus/abakus.py
  src/cogs/cleaning/cleaning.py
  src/cogs/example/example.py
  src/cogs/help/help.py
  src/cogs/mover/mover.py
  src/cogs/soup/soup.py
  src/main.py
Labels: enhancement

#97 fix reminders
  src/cogs/abakus/abakus.py
  src/cogs/abakus/async_helpers.py
  src/cogs/abakus/helper_functions.py
Labels: bug

#98 commentfix
  src/cogs/mover/mover.py
Labels: bug
