Repository God-s-favourite-programmers/ababot, pull requests merged in 2022-10, with the labels that each got.

#109 Workflow
  .github/dependabot.yml
  .github/workflows/docker-image-latest.yml
  .github/workflows/docker-image-release.yml
  .github/workflows/python-app.yml
  Dockerfile
  ababot.code-workspace
  ababot/Cargo.toml
  ababot/bot/Cargo.toml
  ababot/bot/src/commands/dice.rs
  docker-compose.yml
Labels: good first issue

#131 Fix name
  .github/workflows/docker-image-latest.yml
Labels: bug

#132 Move around
  .github/workflows/docker-image-latest.yml
  Dockerfile
Labels: bug

#141 Error reporting
  ababot/bot/src/lib.rs
Labels: bug

#142 Fix macro name bs
  .gitignore
  ababot/bot/src/commands/dice.rs
Labels: bug

#138 Final adjustments do CI/CD
  .github/workflows/docker-image-latest.yml
  .github/workflows/docker-image-release.yml
  docker-compose.yml
Labels: bug

#143 Setup logging
  .gitignore
  ababot/Cargo.lock
  ababot/bot/Cargo.toml
  ababot/bot/src/commands/dice.rs
  ababot/bot/src/commands/knock.rs
  ababot/bot/src/commands/ping.rs
  ababot/bot/src/commands/stonk.rs
  ababot/bot/src/lib.rs
  ababot/bot/src/main.rs
  ababot/bot/src/utils/mod.rs
  docker-compose.yml
Labels: enhancement

#145 Add shared key for caching between jobs
  .github/workflows/docker-image-latest.yml
  .github/workflows/docker-image-release.yml
  .github/workflows/testing.yml
Labels: enhancement
